# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
---
# golangci-lint configuration file made by @ccoVeille
# Source: https://github.com/ccoVeille/golangci-lint-config-examples/
# Author: @ccoVeille
# License: MIT
# Variant: 90-daredevil
# Version: v2.0.0
#
version: "2"

formatters:
  enable:
    # format the code
    - gofmt
    # format the block of imports
    - gci

  settings:
    # format the code with Go standard library
    gofmt:
      # simplify the code
      # https://pkg.go.dev/cmd/gofmt#hdr-The_simplify_command
      simplify: true
      rewrite-rules:
        # replace `interface{}` with `any` in the code on format
        - pattern: "interface{}"
          replacement: "any"

    # make sure imports are always in a deterministic order
    # https://github.com/daixiang0/gci/
    gci: # define the section orders for imports
      sections:
        # Standard section: captures all standard packages.
        - standard
        # Default section: catchall that is not standard or custom
        - default
        # linters that related to local tool, so they should be separated
        - localmodule

run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
  # Make issues output unique by line.
  # Default: true
  uniq-by-line: false

linters:
  # some linters are enabled by default
  # https://golangci-lint.run/usage/linters/
  #
  # enable some extra linters
  default: all
  disable:
    - wsl
  settings:
    usestdlibvars:
      # Suggest the use of http.MethodXX.
      # Default: true
      http-method: true
      # Suggest the use of http.StatusXX.
      # Default: true
      http-status-code: true
      # Suggest the use of time.Weekday.String().
      # Default: true
      time-weekday: true
      # Suggest the use of constants available in time package
      # Default: false
      time-layout: true

    staticcheck:
      # SAxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
      checks: ["all"]

    nolintlint:
      # Enable to require an explanation of nonzero length
      # after each nolint directive.
      # Default: false
      require-explanation: true
      # Enable to require nolint directives to mention the specific
      # linter being suppressed.
      # Default: false
      require-specific: true

    govet:
      enable-all: true
      disable:
        - fieldalignment

    gocritic:
      enable-all: true

    revive:
      enable-all-rules: true
      rules:
        # we must provide configuration for linter that requires them
        # enable-all-rules is OK, but many revive linters expect configuration
        # and cannot work without them

        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-as-argument
        - name: context-as-argument
          arguments:
            - allowTypesBefore: "*testing.T"

        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported
        - name: exported
          arguments:
            # enables checking public methods of private types
            - "checkPrivateReceivers"
            # make error messages clearer
            - "sayRepetitiveInsteadOfStutters"
          
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#line-length-limit
        - name: line-length-limit
          arguments: [120]
        
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#add-constant
        - name: add-constant
          disabled: true # we have mnd for that
        
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#function-length
        - name: function-length
          disabled: true # we have funlen for that

        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#cognitive-complexity
        - name: cognitive-complexity
          severity: warning
          disabled: false
          exclude: [""]
          arguments: [10]
    
    varnamelen:
      ignore-names:
        - err
      # Optional list of variable declarations that should be ignored completely.
      # Entries must be in one of the following forms (see below for examples):
      # - for variables, parameters, named return values, method receivers, or type parameters:
      #   <name> <type>  (<type> can also be a pointer/slice/map/chan/...)
      # - for constants: const <name>
      #
      # Default: []
      ignore-decls:
        - c echo.Context
        - t testing.T
        - T any
        - m map[string]int
        - w http.ResponseWriter
        - r *http.Request

    dupword:
      # Keywords used to ignore detection.
      # Default: []
      ignore: []
      #  - "blah" # this will accept "blah blah …" as a valid duplicate word

    misspell:
      # Correct spellings using locale preferences for US or UK.
      # Setting locale to US will correct the British spelling of 'colour' to 'color'.
      # Default ("") is to use a neutral variety of English.
      locale: US

      # List of words to ignore
      # among the one defined in https://github.com/golangci/misspell/blob/master/words.go
      ignore-rules: []
      #  - valor
      #  - and

      # Extra word corrections.
      extra-words: []
      #  - typo: "whattever"
      #    correction: "whatever"
    depguard:
      # Rules to apply.
      #
      # Variables:
      # - File Variables
      #   Use an exclamation mark `!` to negate a variable.
      #   Example: `!$test` matches any file that is not a go test file.
      #
      #   `$all` - matches all go files
      #   `$test` - matches all go test files
      #
      # - Package Variables
      #
      #   `$gostd` - matches all of go's standard library (Pulled from `GOROOT`)
      #
      # Default (applies if no custom rules are defined): Only allow $gostd in all files.
      rules:
        # Name of a rule.
        main:
          # Defines package matching behavior. Available modes:
          # - `original`: allowed if it doesn't match the deny list and either matches the allow list or the allow list is empty.
          # - `strict`: allowed only if it matches the allow list and either doesn't match the deny list or the allow rule is more specific (longer) than the deny rule.
          # - `lax`: allowed if it doesn't match the deny list or the allow rule is more specific (longer) than the deny rule.
          # Default: "original"
          list-mode: lax
          # List of file globs that will match this list of settings to compare against.
          # By default, if a path is relative, it is relative to the directory where the golangci-lint command is executed.
          # The placeholder '${base-path}' is substituted with a path relative to the mode defined with `run.relative-path-mode`.
          # The placeholder '${config-path}' is substituted with a path relative to the configuration file.
          # Default: $all
          # files:
          #   - "!**/*_a _file.go"
          # List of allowed packages.
          # Entries can be a variable (starting with $), a string prefix, or an exact match (if ending with $).
          # Default: []
          allow:
            - $gostd
            - cobragithub.com/spf13/cobra
          # List of packages that are not allowed.
          # Entries can be a variable (starting with $), a string prefix, or an exact match (if ending with $).
          # Default: []
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package

    exhaustruct:
      exclude:
        - '.+/cobra\.Command$'
        - '.*/http\.Server'
      allow-empty: true
      allow-empty-rx:
        - '.*/http\.Cookie'

output:
  # Order to use when sorting results.
  # Possible values: `file`, `linter`, and `severity`.
  #
  # If the severity values are inside the following list, they are ordered in this order:
  #   1. error
  #   2. warning
  #   3. high
  #   4. medium
  #   5. low
  # Either they are sorted alphabetically.
  #
  # Default: ["file"]
  sort-order:
    - linter
    - severity
    - file # filepath, line, and column.
