# https://github.com/GoogleContainerTools/distroless

# Start by building the application.
FROM golang:1.25.1 as build

ARG BINARY_NAME=app

WORKDIR /go/src/app

# Download packages
COPY go.mod go.sum ./ 
RUN go mod download

# Build app
COPY . . 
RUN CGO_ENABLED=0 go build -o /go/bin/app

# Now copy it into our base image.
FROM debian:12

WORKDIR /

COPY --from=build /go/bin/app /usr/local/bin/${BINARY_NAME}

ENV ALLOW_ROOT_USER=1

EXPOSE 8080

CMD ["app", "server"]
