version: "3"

dotenv: ["project.env", ".env"]

vars:
  MAIN_PACKAGE_PATH: .
  MAIN_BINARY_NAME: "{{ .PROJECT_NAME }}"
  IMG_TAG: "{{ .PROJECT_VERION }}"
  GRC_APP:
    sh: command -v grc 2> /dev/null || exit 0
  LOG_FILE: log.txt
  DEPLOYMENT_TEMPLATE_DIR: ./deployment/plain/template/
  DEPLOYMENT_DIR: ./deployment/plain/
  CONTAINER_TOOL: docker
  BIN_DIR: ./bin
  GOLANGCI_LINT: ./bin/golangci-lint
  GOLANGCI_VERSION: v2.10.1

tasks:
  default:
    desc: run tidy, lint, test
    cmds:
      - task: tidy
      - task: lint
      - task: test

  tidy:
    desc: format code and tidy modfile
    cmds:
      - "{{ .GOLANGCI_LINT }} fmt"
      - go mod tidy -v

  install/lint:
    internal: true
    dir: "{{ .BIN_DIR }}"
    status:
      - test -f golangci-lint
    cmds:
      - curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b . {{ .GOLANGCI_VERSION }}

  lint:
    desc: lint code with golangci-lint
    deps: [install/lint]
    cmds:
      - "{{ .GOLANGCI_LINT }} run {{ .CLI_ARGS }}"

  lint/run:*:
    desc: lint code with spectific linter $ task lint/run:<linter>
    deps: [install/lint]
    vars:
      LINTER: "{{index .MATCH 0}}"
    cmds:
      - "{{ .GOLANGCI_LINT }} run --default=none -E {{ .LINTER }}"

  audit:
    desc: run quality control checks
    cmds:
      - go mod verify
      - go vet ./...
      - task: lint
      - go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...
      - "{{ .GRC_APP }} go test -race -buildvcs -vet=off ./..."
      - task: lint/docker

  upgrade/packages:
    desc: gen new versions of packets
    cmds:
      - go get -u ./...
      - go mod tidy -v

  test:
    desc: run all tests
    cmds:
      - "{{.GRC_APP}} go test -v -race -buildvcs ./..."

  test/cover:
    desc: run all tests and display coverage
    cmds:
      - "{{.GRC_APP}} go test -v -race -buildvcs -coverprofile=/tmp/coverage.out ./..."
      - go tool cover -html=/tmp/coverage.out -o coverage.html

  build:
    desc: build the application
    cmds:
      - go build -o=/tmp/bin/{{ .MAIN_BINARY_NAME }} {{ .MAIN_PACKAGE_PATH }}

  build/image:
    desc: build container image
    cmds:
      - "{{ .CONTAINER_TOOL }} build -t {{ .IMG }}:{{ .IMG_TAG }} --file Dockerfile ."

  build/image/dev:
    desc: build dev container image
    cmds:
      - "{{ .CONTAINER_TOOL }} build -t {{ .IMG }}:dev --file Dockerfile.dev ."

  deployment/template:
    desc: genarate k8s files with env vars
    cmds:
      - envsubst < "{{ .DEPLOYMENT_TEMPLATE_DIR }}deployment.yaml" > "{{.DEPLOYMENT_DIR}}deployment.yaml"
      - envsubst < "{{ .DEPLOYMENT_TEMPLATE_DIR }}service.yaml" > "{{.DEPLOYMENT_DIR}}service.yaml"

  kind/deploy:
    desc: deploy to kind
    deps:
      - deployment/template
      - build/image
    cmds:
      - docker exec kind-control-plane crictl rmi {{ .IMG }}:{{ .IMG_TAG }} | true
      - kind load docker-image -q {{ .IMG }}:{{ .IMG_TAG }}
      - kubectl delete -f deployment/plain --ignore-not-found
      - kubectl apply -f deployment/plain --wait

  run/server:
    desc: run the application
    deps: [build]
    cmds:
      - /tmp/bin/{{.MAIN_BINARY_NAME}} server {{ .CLI_ARGS }}

  run/server/log:
    desc: run the application with stdout to file
    deps: [build]
    cmds:
      - mkdir -p /tmp/log/
      - /tmp/bin/{{.MAIN_BINARY_NAME}} server {{ .CLI_ARGS }} > /tmp/log/{{ .LOG_FILE }}

  run/hl:
    desc: watch log with hl
    silent: true
    cmds:
      - hl --follow /tmp/log/{{ .LOG_FILE }}

  run/server/live:
    desc: run the application with reloading on file changes
    cmds:
      - go run github.com/cosmtrek/air@v1.43.0
        --build.cmd "task build" --build.bin "/tmp/bin/{{ .MAIN_BINARY_NAME }}" --build.delay "100"
        --misc.clean_on_exit "true"
        --build.send_interrupt "true"
        --build.kill_delay "1000000000"
        --
        server
        {{ .CLI_ARGS }}
